modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "GNU GPL3"

[[mods]]
modId = "multiblockmachine"
version = "${version}"
displayName = "Multiblock Machine"
authors = "6LeoMC"
description = '''
'''
#logoFile = ""

[[dependencies.multiblockmachine]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.multiblockmachine]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.multiblockmachine]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"