modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://www.github.com/yzl210/MultiblockMachine/issues"
license = "GNU GPLv3"

[[mods]]
modId = "multiblockmachine"
version = "${version}"
displayName = "Multiblock Machine"
authors = "6LeoMC"
description = '''
'''
#logoFile = ""

[[dependencies.multiblockmachine]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.multiblockmachine]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.multiblockmachine]]
modId = "architectury"
mandatory = true
versionRange = "[3.7.26,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.multiblockmachine]]
modId = "cloth_config"
mandatory = true
versionRange = "[6.2.5.7,)"
ordering = "AFTER"
side = "BOTH"